### ISSUE TITLE
playgame fails if log directory does not exist

### ISSUE THREAD

**Issue by akaps** [akaps/hanabi_ai#26]
Create a script for playgame.py that makes logs to a missing directory. Need to check if the path exists and then make the directory if not
HOWEVER...

> Here's an interesting question, should we implicitly save to results, or still require the script to call it out? option 1 makes sure the directories are clean. Option 2 avoids confusing unintended behavior

**Comment by T1bzt** [comment]
Let me help you! Can I solve this issue?

**Comment by akaps** [comment]
Sure. please fork from master and create a pull request with your solution. Please test the following scenarios with your solution:

- [ ] running tournament.sh and sample.sh (paths with directory that exist)
- [ ] choosing a log and std_err path with no directory
- [ ] choosing a log and std_err path with a missing directory

**Comment by T1bzt** [comment]
Hi, im new to GitHub. I solved the problem what should I do next?
